
# resume information
resume-index = 3466
seed = 8247861252873117262
rate = 100       
shard = 1/1
banners = true
nocapture = servername


adapter-ip = 192.168.58.200
# TARGET SELECTION (IP, PORTS, EXCLUDES)
ports = 22-5000
range = 37.119.209.0/24

